"""Tests for the WOPC game config Lua file generator."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest

from launcher.game_config import FACTIONS, write_game_config


@pytest.fixture()
def config_dir(tmp_path: Path) -> Path:
    """Provide a temp dir as WOPC_BIN for config output."""
    return tmp_path


class TestWriteGameConfig:
    """Test write_game_config() generates valid Lua files."""

    def test_default_config(self, config_dir: Path) -> None:
        """Default call produces valid Lua with 1 human + 1 AI."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        assert path.exists()
        lua = path.read_text(encoding="utf-8")

        # Header comment
        assert "Auto-generated by WOPC launcher" in lua

        # Scenario file
        assert "ScenarioFile = '/maps/Caldera/Caldera_scenario.lua'" in lua

        # Human player
        assert "Human = true" in lua
        assert "PlayerName = 'Player'" in lua

        # Default AI opponent
        assert "Human = false" in lua
        assert "AIPersonality = 'medium'" in lua

        # Lua syntax: single braces, not double
        assert "{{" not in lua
        assert "}}" not in lua

    def test_custom_player(self, config_dir: Path) -> None:
        """Custom player name and faction are written correctly."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/SCMP_002/SCMP_002_scenario.lua",
                player_name="TestUser",
                player_faction="cybran",
            )

        lua = path.read_text(encoding="utf-8")
        assert "PlayerName = 'TestUser'" in lua
        assert f"Faction = {FACTIONS['cybran']}" in lua

    def test_multiple_ai_opponents(self, config_dir: Path) -> None:
        """Multiple AI opponents are all included."""
        ais = [
            {"name": "AI Easy", "faction": "aeon", "ai": "easy", "team": 2},
            {"name": "AI Rush", "faction": "uef", "ai": "rush", "team": 2},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        assert "PlayerName = 'AI Easy'" in lua
        assert "AIPersonality = 'easy'" in lua
        assert "PlayerName = 'AI Rush'" in lua
        assert "AIPersonality = 'rush'" in lua
        # Should have 3 players total (1 human + 2 AI)
        assert lua.count("Human = true") == 1
        assert lua.count("Human = false") == 2

    def test_empty_ai_list(self, config_dir: Path) -> None:
        """Empty AI list produces only the human player."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                ai_opponents=[],
            )

        lua = path.read_text(encoding="utf-8")
        assert lua.count("Human = true") == 1
        assert "Human = false" not in lua

    def test_game_options(self, config_dir: Path) -> None:
        """Game option overrides are written."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                game_options={"UnitCap": "2000", "FogOfWar": "none"},
            )

        lua = path.read_text(encoding="utf-8")
        assert "UnitCap = '2000'" in lua
        assert "FogOfWar = 'none'" in lua

    def test_no_game_options(self, config_dir: Path) -> None:
        """No game options produces empty GameOptions table."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        lua = path.read_text(encoding="utf-8")
        assert "GameOptions = {" in lua

    def test_lua_escaping(self, config_dir: Path) -> None:
        """Special characters in names are escaped for Lua."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                player_name="O'Brien",
            )

        lua = path.read_text(encoding="utf-8")
        assert "PlayerName = 'O\\'Brien'" in lua

    def test_faction_defaults_to_random(self, config_dir: Path) -> None:
        """Unknown faction defaults to 5 (random)."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                player_faction="unknown_faction",
            )

        lua = path.read_text(encoding="utf-8")
        assert "Faction = 5" in lua

    def test_output_path(self, config_dir: Path) -> None:
        """Output file is written to WOPC_BIN/wopc_game_config.lua."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        assert path == config_dir / "wopc_game_config.lua"

    def test_creates_parent_directories(self, tmp_path: Path) -> None:
        """Creates parent dirs if WOPC_BIN doesn't exist yet."""
        nested = tmp_path / "a" / "b" / "c"
        with patch("launcher.game_config.WOPC_BIN", nested):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        assert path.exists()

    def test_active_mods_written(self, config_dir: Path) -> None:
        """Active mod UIDs are written to config for quickstart.lua."""
        uids = ["9e8ea941-c306-4751-b367-e00000000302", "9e8ea941-c306-4751-b367-a11000000502"]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                active_mod_uids=uids,
            )

        lua = path.read_text(encoding="utf-8")
        assert "ActiveMods = {" in lua
        assert "'9e8ea941-c306-4751-b367-e00000000302'" in lua
        assert "'9e8ea941-c306-4751-b367-a11000000502'" in lua

    def test_no_active_mods(self, config_dir: Path) -> None:
        """Empty ActiveMods table when no mods are active."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        lua = path.read_text(encoding="utf-8")
        assert "ActiveMods = {" in lua

    def test_start_spots_increment(self, config_dir: Path) -> None:
        """Each player gets an incrementing StartSpot and PlayerColor."""
        ais = [
            {"name": "AI 1", "faction": "random", "ai": "medium", "team": 2},
            {"name": "AI 2", "faction": "random", "ai": "medium", "team": 2},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        assert "StartSpot = 1" in lua  # human
        assert "StartSpot = 2" in lua  # AI 1
        assert "StartSpot = 3" in lua  # AI 2
        assert "PlayerColor = 1" in lua
        assert "PlayerColor = 2" in lua
        assert "PlayerColor = 3" in lua


class TestPlayerColors:
    """Test player color assignment in game config."""

    def test_default_human_color(self, config_dir: Path) -> None:
        """Default human color is 1."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        lua = path.read_text(encoding="utf-8")
        # Human player slot has color 1
        lines = lua.split("\n")
        # Find the human block and check color
        in_human = False
        for line in lines:
            if "Human = true" in line:
                in_human = True
            if in_human and "PlayerColor" in line:
                assert "PlayerColor = 1" in line
                break

    def test_custom_human_color(self, config_dir: Path) -> None:
        """Custom human color is written correctly."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                player_color=5,
            )

        lua = path.read_text(encoding="utf-8")
        lines = lua.split("\n")
        in_human = False
        for line in lines:
            if "Human = true" in line:
                in_human = True
            if in_human and "PlayerColor" in line:
                assert "PlayerColor = 5" in line
                break

    def test_ai_color_from_dict(self, config_dir: Path) -> None:
        """AI color comes from the ai_opponents dict."""
        ais = [
            {"name": "AI 1", "faction": "random", "ai": "medium", "team": 2, "color": 3},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        lines = lua.split("\n")
        in_ai = False
        for line in lines:
            if "Human = false" in line:
                in_ai = True
            if in_ai and "PlayerColor" in line:
                assert "PlayerColor = 3" in line
                break

    def test_ai_color_defaults_to_slot_index(self, config_dir: Path) -> None:
        """AI without explicit color defaults to its slot index."""
        ais = [
            {"name": "AI 1", "faction": "random", "ai": "medium", "team": 2},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        lines = lua.split("\n")
        in_ai = False
        for line in lines:
            if "Human = false" in line:
                in_ai = True
            if in_ai and "PlayerColor" in line:
                # Slot 2 (first AI after human slot 1)
                assert "PlayerColor = 2" in line
                break

    def test_victory_condition_mapping(self, config_dir: Path) -> None:
        """Victory conditions map display names to engine values correctly."""
        # Test Supremacy → domination (the tricky mapping)
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                game_options={"Victory": "domination"},
            )

        lua = path.read_text(encoding="utf-8")
        assert "Victory = 'domination'" in lua


class TestArmyPositionMapping:
    """Test that Players array index == StartSpot for correct ARMY_N assignment."""

    def test_contiguous_positions_no_fillers(self, config_dir: Path) -> None:
        """No civilian fillers when positions are 1, 2, 3 (contiguous)."""
        ais = [
            {"name": "AI 1", "faction": "random", "ai": "medium", "team": 2, "start_spot": 2},
            {"name": "AI 2", "faction": "random", "ai": "medium", "team": 2, "start_spot": 3},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/test/test_scenario.lua",
                player_start_spot=1,
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        assert "Civilian = true" not in lua
        assert lua.count("Human = true") == 1
        assert lua.count("Human = false") == 2

    def test_gap_filled_with_civilian(self, config_dir: Path) -> None:
        """Gap at position 3 gets a civilian filler when players are at 1, 2, 4."""
        ais = [
            {"name": "AI 1", "faction": "aeon", "ai": "medium", "team": 2, "start_spot": 2},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/test/test_scenario.lua",
                player_start_spot=4,
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        # Should have 4 entries: AI at 2, civilian at 1 and 3, human at 4
        # Wait — human at 4, AI at 2. Positions 1 and 3 are gaps.
        assert lua.count("Civilian = true") == 2  # positions 1 and 3
        assert "Human = true" in lua

    def test_human_at_position_4_is_fourth_in_array(self, config_dir: Path) -> None:
        """Human at StartSpot 4 must be the 4th entry so engine assigns ARMY_4."""
        ais = [
            {"name": "AI 1", "faction": "uef", "ai": "easy", "team": 2, "start_spot": 1},
            {"name": "AI 2", "faction": "aeon", "ai": "medium", "team": 3, "start_spot": 2},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/test/test_scenario.lua",
                player_name="TestHuman",
                player_start_spot=4,
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        # Parse the Players block to verify ordering
        lines = lua.split("\n")
        player_blocks: list[str] = []
        current_block: list[str] = []
        in_players = False
        for line in lines:
            if "Players = {" in line:
                in_players = True
                continue
            if in_players:
                if line.strip() == "},":
                    if current_block:
                        player_blocks.append("\n".join(current_block))
                        current_block = []
                    # Check if this is the end of Players
                    continue
                if line.strip() == "{":
                    current_block = []
                current_block.append(line)

        # Block 0 = position 1 (AI 1), Block 1 = position 2 (AI 2),
        # Block 2 = position 3 (civilian filler), Block 3 = position 4 (human)
        assert len(player_blocks) >= 4
        assert "AI 1" in player_blocks[0]
        assert "AI 2" in player_blocks[1]
        assert "Civilian = true" in player_blocks[2]
        assert "TestHuman" in player_blocks[3]

    def test_single_player_high_position(self, config_dir: Path) -> None:
        """Solo human at position 5 creates 4 civilian fillers before them."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/test/test_scenario.lua",
                player_start_spot=5,
                ai_opponents=[],
            )

        lua = path.read_text(encoding="utf-8")
        assert lua.count("Civilian = true") == 4  # positions 1-4


class TestMultiplayerConfig:
    """Test multiplayer fields (ExpectedHumans, IsHost)."""

    def test_default_solo(self, config_dir: Path) -> None:
        """Default config is solo: ExpectedHumans=1, IsHost=true."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        lua = path.read_text(encoding="utf-8")
        assert "ExpectedHumans = 1" in lua
        assert "IsHost = true" in lua

    def test_multiplayer_host(self, config_dir: Path) -> None:
        """Host config has ExpectedHumans > 1 and IsHost = true."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                expected_humans=4,
                is_host=True,
            )

        lua = path.read_text(encoding="utf-8")
        assert "ExpectedHumans = 4" in lua
        assert "IsHost = true" in lua

    def test_multiplayer_joiner(self, config_dir: Path) -> None:
        """Joiner config has IsHost = false."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                expected_humans=2,
                is_host=False,
            )

        lua = path.read_text(encoding="utf-8")
        assert "ExpectedHumans = 2" in lua
        assert "IsHost = false" in lua
