"""Tests for the WOPC game config Lua file generator."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest

from launcher.game_config import FACTIONS, write_game_config


@pytest.fixture()
def config_dir(tmp_path: Path) -> Path:
    """Provide a temp dir as WOPC_BIN for config output."""
    return tmp_path


class TestWriteGameConfig:
    """Test write_game_config() generates valid Lua files."""

    def test_default_config(self, config_dir: Path) -> None:
        """Default call produces valid Lua with 1 human + 1 AI."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        assert path.exists()
        lua = path.read_text(encoding="utf-8")

        # Header comment
        assert "Auto-generated by WOPC launcher" in lua

        # Scenario file
        assert "ScenarioFile = '/maps/Caldera/Caldera_scenario.lua'" in lua

        # Human player
        assert "Human = true" in lua
        assert "PlayerName = 'Player'" in lua

        # Default AI opponent
        assert "Human = false" in lua
        assert "AIPersonality = 'medium'" in lua

        # Lua syntax: single braces, not double
        assert "{{" not in lua
        assert "}}" not in lua

    def test_custom_player(self, config_dir: Path) -> None:
        """Custom player name and faction are written correctly."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/SCMP_002/SCMP_002_scenario.lua",
                player_name="TestUser",
                player_faction="cybran",
            )

        lua = path.read_text(encoding="utf-8")
        assert "PlayerName = 'TestUser'" in lua
        assert f"Faction = {FACTIONS['cybran']}" in lua

    def test_multiple_ai_opponents(self, config_dir: Path) -> None:
        """Multiple AI opponents are all included."""
        ais = [
            {"name": "AI Easy", "faction": "aeon", "ai": "easy", "team": 2},
            {"name": "AI Rush", "faction": "uef", "ai": "rush", "team": 2},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        assert "PlayerName = 'AI Easy'" in lua
        assert "AIPersonality = 'easy'" in lua
        assert "PlayerName = 'AI Rush'" in lua
        assert "AIPersonality = 'rush'" in lua
        # Should have 3 players total (1 human + 2 AI)
        assert lua.count("Human = true") == 1
        assert lua.count("Human = false") == 2

    def test_empty_ai_list(self, config_dir: Path) -> None:
        """Empty AI list produces only the human player."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                ai_opponents=[],
            )

        lua = path.read_text(encoding="utf-8")
        assert lua.count("Human = true") == 1
        assert "Human = false" not in lua

    def test_game_options(self, config_dir: Path) -> None:
        """Game option overrides are written."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                game_options={"UnitCap": "2000", "FogOfWar": "none"},
            )

        lua = path.read_text(encoding="utf-8")
        assert "UnitCap = '2000'" in lua
        assert "FogOfWar = 'none'" in lua

    def test_no_game_options(self, config_dir: Path) -> None:
        """No game options produces empty GameOptions table."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        lua = path.read_text(encoding="utf-8")
        assert "GameOptions = {" in lua

    def test_lua_escaping(self, config_dir: Path) -> None:
        """Special characters in names are escaped for Lua."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                player_name="O'Brien",
            )

        lua = path.read_text(encoding="utf-8")
        assert "PlayerName = 'O\\'Brien'" in lua

    def test_faction_defaults_to_random(self, config_dir: Path) -> None:
        """Unknown faction defaults to 5 (random)."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                player_faction="unknown_faction",
            )

        lua = path.read_text(encoding="utf-8")
        assert "Faction = 5" in lua

    def test_output_path(self, config_dir: Path) -> None:
        """Output file is written to WOPC_BIN/wopc_game_config.lua."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        assert path == config_dir / "wopc_game_config.lua"

    def test_creates_parent_directories(self, tmp_path: Path) -> None:
        """Creates parent dirs if WOPC_BIN doesn't exist yet."""
        nested = tmp_path / "a" / "b" / "c"
        with patch("launcher.game_config.WOPC_BIN", nested):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        assert path.exists()

    def test_active_mods_written(self, config_dir: Path) -> None:
        """Active mod UIDs are written to config for quickstart.lua."""
        uids = ["9e8ea941-c306-4751-b367-e00000000302", "9e8ea941-c306-4751-b367-a11000000502"]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                active_mod_uids=uids,
            )

        lua = path.read_text(encoding="utf-8")
        assert "ActiveMods = {" in lua
        assert "'9e8ea941-c306-4751-b367-e00000000302'" in lua
        assert "'9e8ea941-c306-4751-b367-a11000000502'" in lua

    def test_no_active_mods(self, config_dir: Path) -> None:
        """Empty ActiveMods table when no mods are active."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        lua = path.read_text(encoding="utf-8")
        assert "ActiveMods = {" in lua

    def test_start_spots_increment(self, config_dir: Path) -> None:
        """Each player gets an incrementing StartSpot and PlayerColor."""
        ais = [
            {"name": "AI 1", "faction": "random", "ai": "medium", "team": 2},
            {"name": "AI 2", "faction": "random", "ai": "medium", "team": 2},
        ]
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                ai_opponents=ais,
            )

        lua = path.read_text(encoding="utf-8")
        assert "StartSpot = 1" in lua  # human
        assert "StartSpot = 2" in lua  # AI 1
        assert "StartSpot = 3" in lua  # AI 2
        assert "PlayerColor = 1" in lua
        assert "PlayerColor = 2" in lua
        assert "PlayerColor = 3" in lua


class TestMultiplayerConfig:
    """Test multiplayer fields (ExpectedHumans, IsHost)."""

    def test_default_solo(self, config_dir: Path) -> None:
        """Default config is solo: ExpectedHumans=1, IsHost=true."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config("/maps/Caldera/Caldera_scenario.lua")

        lua = path.read_text(encoding="utf-8")
        assert "ExpectedHumans = 1" in lua
        assert "IsHost = true" in lua

    def test_multiplayer_host(self, config_dir: Path) -> None:
        """Host config has ExpectedHumans > 1 and IsHost = true."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                expected_humans=4,
                is_host=True,
            )

        lua = path.read_text(encoding="utf-8")
        assert "ExpectedHumans = 4" in lua
        assert "IsHost = true" in lua

    def test_multiplayer_joiner(self, config_dir: Path) -> None:
        """Joiner config has IsHost = false."""
        with patch("launcher.game_config.WOPC_BIN", config_dir):
            path = write_game_config(
                "/maps/Caldera/Caldera_scenario.lua",
                expected_humans=2,
                is_host=False,
            )

        lua = path.read_text(encoding="utf-8")
        assert "ExpectedHumans = 2" in lua
        assert "IsHost = false" in lua
