"""WOPC deploy - creates the WOPC game directory and copies/symlinks content."""

import logging
import shutil
import zipfile
from pathlib import Path

from launcher import config

logger = logging.getLogger("wopc.deploy")


def link_or_copy(src: Path, dst: Path) -> None:
    """Create a symlink, falling back to copy if symlinks need admin."""
    if dst.exists() or dst.is_symlink():
        return  # already exists
    try:
        if src.is_dir():
            dst.symlink_to(src, target_is_directory=True)
        else:
            dst.symlink_to(src)
        logger.info("  symlink %s -> %s", dst.name, src)
    except OSError:
        if src.is_dir():
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)
        logger.info("  copied  %s", dst.name)


def copy_file(src: Path, dst: Path) -> None:
    """Copy a single file, skip if already exists."""
    if dst.exists():
        return
    shutil.copy2(src, dst)
    logger.info("  copied  %s", dst.name)


def run_setup(repo_init_dir: Path) -> None:
    """Create the WOPC game directory at C:\\ProgramData\\WOPC\\ and populate it.

    Args:
        repo_init_dir: path to the init/ directory in the repo (contains init_wopc.lua)
    """
    logger.info("\n=== WOPC Setup v%s ===\n", config.VERSION)
    logger.info("WOPC directory: %s", config.WOPC_ROOT)

    # Create directory structure
    for d in [config.WOPC_ROOT, config.WOPC_BIN, config.WOPC_GAMEDATA]:
        d.mkdir(parents=True, exist_ok=True)

    # --- Step 1: Copy exe + DLLs from Steam SCFA/bin/ ---
    # Prefer FAF-patched exe if available, fall back to stock
    patched_exe = config.PATCH_BUILD_DIR / "ForgedAlliance_exxt.exe"
    exe_dst = config.WOPC_BIN / config.GAME_EXE
    if patched_exe.is_file():
        logger.info("\n[1/6] Copying FAF-patched game binaries")
        # Always overwrite exe with latest patched version
        shutil.copy2(patched_exe, exe_dst)
        logger.info("  copied  %s (FAF-patched)", config.GAME_EXE)
    else:
        logger.info("\n[1/6] Copying game binaries from %s", config.SCFA_BIN)
        logger.info("  NOTE: Using stock exe. Run 'wopc patch' to build FAF-patched version.")

    missing = []
    for fname in config.BIN_FILES:
        src = config.SCFA_BIN / fname
        dst = config.WOPC_BIN / fname
        # Skip exe if we already copied the patched version
        if fname == config.GAME_EXE and dst.exists():
            continue
        if src.exists():
            copy_file(src, dst)
        else:
            missing.append(fname)
    if missing:
        logger.warning("  WARNING: missing files: %s", ", ".join(missing))

    # --- Step 2: Copy LOUD bin files (icons SCD, CommonDataPath) ---
    logger.info("\n[2/6] Copying LOUD bin files from %s", config.LOUD_BIN)
    for fname in config.LOUD_BIN_FILES:
        src = config.LOUD_BIN / fname
        if src.exists():
            copy_file(src, config.WOPC_BIN / fname)
        else:
            logger.warning("  WARNING: missing %s", fname)

    # --- Step 3: Copy init files from repo ---
    logger.info("\n[3/6] Copying init files from repo")
    for fname in ["init_wopc.lua", "CommonDataPath.lua"]:
        src = repo_init_dir / fname
        dst = config.WOPC_BIN / fname
        if src.exists():
            # Always overwrite init files (they may have been updated in repo)
            shutil.copy2(src, dst)
            logger.info("  copied  %s", fname)
        else:
            logger.warning("  WARNING: missing %s in repo init/ directory", fname)

    # Generate wopc_paths.lua with the absolute SCFA path
    # (WOPC lives in ProgramData, not inside SCFA, so we need this)
    scfa_escaped = str(config.SCFA_STEAM).replace("\\", "\\\\")
    paths_lua = config.WOPC_BIN / "wopc_paths.lua"
    paths_lua.write_text(
        f'-- Auto-generated by WOPC setup -- do not edit\nSCFARoot = "{scfa_escaped}"\n'
    )
    logger.info("  generated wopc_paths.lua (SCFA = %s)", config.SCFA_STEAM)

    # --- Step 4: Symlink/copy LOUD content ---
    logger.info("\n[4/6] Linking LOUD content")

    # Gamedata: symlink individual SCD files (not the directory itself,
    # because we'll add wopc_patches.scd alongside them)
    if config.LOUD_GAMEDATA.exists():
        for scd in sorted(config.LOUD_GAMEDATA.glob("*.scd")):
            link_or_copy(scd, config.WOPC_GAMEDATA / scd.name)
    else:
        logger.warning("  WARNING: LOUD gamedata not found at %s", config.LOUD_GAMEDATA)

    # Build faf_ui.scd
    faf_ui_src = config.REPO_FAF_UI
    faf_ui_dst = config.WOPC_GAMEDATA / config.FAF_UI_SCD
    if faf_ui_src.exists():
        logger.info("  building %s", config.FAF_UI_SCD)
        with zipfile.ZipFile(faf_ui_dst, "w", zipfile.ZIP_DEFLATED) as zf:
            # The FAF UI repo has many files, but the engine only cares about specific dirs
            for target_dir in ["lua", "modules", "ui", "loc"]:
                dir_path = faf_ui_src / target_dir
                if dir_path.exists():
                    for file_path in dir_path.rglob("*"):
                        if file_path.is_file():
                            arcname = file_path.relative_to(faf_ui_src)
                            zf.write(file_path, arcname)
    else:
        logger.warning("  WARNING: %s not found. Did you initialize submodules?", faf_ui_src)

    # Build wopc_patches.scd
    wopc_patches_src = config.REPO_WOPC_PATCHES
    wopc_patches_dst = config.WOPC_GAMEDATA / config.WOPC_PATCHES_SCD
    if wopc_patches_src.exists():
        logger.info("  building %s", config.WOPC_PATCHES_SCD)
        with zipfile.ZipFile(wopc_patches_dst, "w", zipfile.ZIP_DEFLATED) as zf:
            for file_path in wopc_patches_src.rglob("*"):
                if file_path.is_file():
                    arcname = file_path.relative_to(wopc_patches_src)
                    zf.write(file_path, arcname)
    else:
        logger.warning("  WARNING: %s not found", wopc_patches_src)

    # Maps, sounds: symlink entire directories
    if config.LOUD_MAPS.exists():
        link_or_copy(config.LOUD_MAPS, config.WOPC_MAPS)
    if config.LOUD_SOUNDS.exists():
        link_or_copy(config.LOUD_SOUNDS, config.WOPC_SOUNDS)

    # --- Step 5: Copy usermods (not symlink - user may add/remove mods) ---
    logger.info("\n[5/6] Copying user mods")
    if config.LOUD_USERMODS.exists() and not config.WOPC_USERMODS.exists():
        shutil.copytree(config.LOUD_USERMODS, config.WOPC_USERMODS)
        logger.info(
            "  copied usermods/ (%d files)", sum(1 for _ in config.WOPC_USERMODS.rglob("*"))
        )
    elif config.WOPC_USERMODS.exists():
        logger.info("  usermods/ already exists, skipping")
    else:
        config.WOPC_USERMODS.mkdir(parents=True, exist_ok=True)
        logger.info("  created empty usermods/")

    # --- Step 6: Link/create usermaps ---
    logger.info("\n[6/6] Setting up user maps")
    if config.LOUD_USERMAPS.exists():
        link_or_copy(config.LOUD_USERMAPS, config.WOPC_USERMAPS)
    else:
        config.WOPC_USERMAPS.mkdir(parents=True, exist_ok=True)
        logger.info("  created empty usermaps/")

    logger.info("\n=== Setup complete ===")
    logger.info("Game directory: %s", config.WOPC_ROOT)
    logger.info("Launch with:    wopc launch")
