"""Write the WOPC game configuration Lua file for quickstart.

The launcher calls ``write_game_config()`` before each game launch.
The generated ``wopc_game_config.lua`` is placed in ``WOPC_BIN``
and read by ``wopc_patches/lua/wopc/quickstart.lua`` at runtime.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from launcher.config import WOPC_BIN

logger = logging.getLogger("wopc.game_config")

# Faction constants — match SCFA's lua/factions.lua indexing
FACTIONS = {"uef": 1, "aeon": 2, "cybran": 3, "seraphim": 4, "random": 5}

# Default AI personality keys (from faf_ui aitypes.lua)
AI_TYPES = ("easy", "medium", "adaptive", "rush", "turtle", "tech", "random")


def write_game_config(
    scenario_file: str,
    player_name: str = "Player",
    player_faction: str = "random",
    ai_opponents: list[dict[str, Any]] | None = None,
    game_options: dict[str, str] | None = None,
) -> Path:
    """Write ``wopc_game_config.lua`` to ``WOPC_BIN``.

    Parameters
    ----------
    scenario_file:
        VFS path to the map scenario file, e.g.
        ``/maps/Caldera/Caldera_scenario.lua``.
    player_name:
        Human player's display name.
    player_faction:
        Faction key for the human player (uef/aeon/cybran/seraphim/random).
    ai_opponents:
        List of AI player dicts, each with keys:
        ``name`` (str), ``faction`` (str), ``ai`` (str), ``team`` (int).
        If None, a single "medium" AI opponent is added.
    game_options:
        Optional dict of game option overrides (e.g. ``{"UnitCap": "2000"}``).

    Returns
    -------
    Path to the generated file.
    """
    if ai_opponents is None:
        ai_opponents = [{"name": "AI: Normal", "faction": "random", "ai": "medium", "team": 2}]

    output = WOPC_BIN / "wopc_game_config.lua"

    player_faction_num = FACTIONS.get(player_faction.lower(), 5)

    players_lua = []

    # Slot 1: human player
    players_lua.append(
        "        {\n"
        "            Human = true,\n"
        f"            PlayerName = '{_escape_lua(player_name)}',\n"
        f"            Faction = {player_faction_num},\n"
        "            Team = 1,\n"
        "            PlayerColor = 1,\n"
        "            StartSpot = 1,\n"
        "            AIPersonality = '',\n"
        "        }"
    )

    # AI slots
    for idx, ai in enumerate(ai_opponents, start=2):
        ai_name = ai.get("name", f"AI {idx}")
        ai_faction = FACTIONS.get(ai.get("faction", "random").lower(), 5)
        ai_key = ai.get("ai", "medium")
        ai_team = ai.get("team", 1)

        players_lua.append(
            "        {\n"
            "            Human = false,\n"
            f"            PlayerName = '{_escape_lua(ai_name)}',\n"
            f"            Faction = {ai_faction},\n"
            f"            Team = {ai_team},\n"
            f"            PlayerColor = {idx},\n"
            f"            StartSpot = {idx},\n"
            f"            AIPersonality = '{_escape_lua(ai_key)}',\n"
            "        }"
        )

    players_block = ",\n".join(players_lua)

    # Game options overrides
    options_lines = []
    if game_options:
        for key, val in game_options.items():
            options_lines.append(f"        {key} = '{_escape_lua(str(val))}',")
    options_block = "\n".join(options_lines)

    lua = f"""\
-- Auto-generated by WOPC launcher — do not edit
-- Read by lua/wopc/quickstart.lua at game launch
return {{
    ScenarioFile = '{_escape_lua(scenario_file)}',
    Players = {{
{players_block}
    }},
    GameOptions = {{
{options_block}
    }},
}}
"""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(lua, encoding="utf-8")
    logger.info("Wrote game config to %s", output)
    return output


def _escape_lua(s: str) -> str:
    """Escape a string for embedding in a Lua single-quoted literal."""
    return s.replace("\\", "\\\\").replace("'", "\\'")
