"""Dynamic init_wopc.lua generator.

Writes a fresh ``init_wopc.lua`` into ``SCFA\\WOPC\\bin\\``
every time the user clicks **PLAY MATCH**.  This allows content packs
(gamedata SCDs) to be toggled on/off from the launcher UI — disabled
packs are simply omitted from the mount list.

The template is identical to ``init/init_wopc.lua`` in the repo, but
replaces the wildcard ``mount_dir(... '\\\\*.scd', '/')`` with explicit
lines for each enabled SCD.

Content pack state management (labels, toggling, enabled packs) lives
in ``launcher.mods`` — this module is a pure template renderer.
"""

import logging
from pathlib import Path

from launcher import config, mods

logger = logging.getLogger("wopc.init_generator")


def get_toggleable_scds() -> list[str]:
    """Delegate to mods.get_toggleable_scds()."""
    return mods.get_toggleable_scds()


def get_enabled_packs() -> list[str]:
    """Delegate to mods.get_enabled_packs()."""
    return mods.get_enabled_packs()


def set_pack_state(scd_name: str, enabled: bool) -> None:
    """Delegate to mods.set_pack_state()."""
    mods.set_pack_state(scd_name, enabled)


def generate_init_lua() -> Path:
    """Write a fresh ``init_wopc.lua`` to ``WOPC_BIN``.

    Returns the path to the generated file.
    """
    output = config.WOPC_BIN / "init_wopc.lua"

    # Determine which SCDs to mount
    enabled_packs = get_enabled_packs()
    core_on_disk = sorted(s for s in mods.CORE_SCDS if (config.WOPC_GAMEDATA / s).exists())

    # Build the gamedata mount lines
    gamedata_mounts = []
    for scd in core_on_disk:
        gamedata_mounts.append(f"mount_dir(WOPCRoot .. '\\\\gamedata\\\\{scd}', '/')")
    for scd in enabled_packs:
        gamedata_mounts.append(f"mount_dir(WOPCRoot .. '\\\\gamedata\\\\{scd}', '/')")

    gamedata_block = "\n".join(gamedata_mounts)

    # User mods are mounted via the engine's mount_mods() function which
    # handles mod metadata, dependencies, and ordering automatically.
    # Individual mod toggling is not yet supported (requires engine work).

    lua_content = f"""\
-- =============================================================================
-- init_wopc.lua — WOPC init file (AUTO-GENERATED)
-- With Our Powers Combined: Standalone SCFA gameplay
--
-- THIS FILE IS REGENERATED BY THE LAUNCHER BEFORE EACH GAME LAUNCH.
-- Do not edit by hand — changes will be overwritten.
--
-- Mount order determines content priority (first-added = highest priority
-- for the engine's VFS file lookup — earlier mounts shadow later ones):
--   1. Bundled strategic icons  (from WOPC/bin/)
--   2. Content pack SCDs        (unit packs — toggleable, disabled by default)
--   3. Bundled maps and sounds
--   4. WOPC core SCD            (game logic + our fixes)
--   5. Vanilla SCFA content     (fonts, textures, effects, units, loc, etc.)
--   6. User maps
--   7. Server mods              (content pack mods — shared by all players)
--   8. User mods                (personal mods via mount_mods)
-- =============================================================================

do
dofile(InitFileDir.."\\\\CommonDataPath.lua");

-- Resolve WOPC root: bin's parent directory
WOPCRoot = InitFileDir .. '\\\\..'

-- Load SCFA path from generated config (written by setup)
-- This file sets: SCFARoot = WOPCRoot .. "\\\\.."
dofile(InitFileDir.."\\\\wopc_paths.lua");

-- =========================================================================
-- 1. Bundled strategic icons
-- =========================================================================
mount_dir(InitFileDir .. '\\\\BrewLAN-StrategicIconsOverhaul-LARGE-classic.scd', '/')

-- =========================================================================
-- 2. Content pack SCDs (unit packs — disabled by default)
-- =========================================================================
{gamedata_block}

-- =========================================================================
-- 3. Bundled maps and sounds
-- =========================================================================
mount_dir(WOPCRoot .. '\\\\maps', '/maps')
mount_dir(WOPCRoot .. '\\\\sounds', '/sounds')

-- =========================================================================
-- 4. WOPC core SCD (game logic + patches + vanilla gap-fills)
-- Must be mounted BEFORE vanilla SCDs so the engine's VFS finds our
-- files first (first-added = highest priority in SCFA's VFS).
-- =========================================================================
local wopc_core = WOPCRoot .. '\\\\gamedata\\\\wopc_core.scd'
mount_dir(wopc_core, '/')

-- =========================================================================
-- 5. Vanilla SCFA content (assets + gameplay data from Steam install)
-- Mounted AFTER wopc_core so our files take priority.  Vanilla provides
-- assets we don't replace (unmodified units, textures, etc.).
-- wopc_core.scd replaces lua.scd, mohodata.scd, moholua.scd, and
-- schook.scd — those are NOT mounted here.
-- =========================================================================
mount_dir(SCFARoot .. '\\\\fonts', '/fonts')
mount_dir(SCFARoot .. '\\\\gamedata\\\\textures.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\effects.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\env.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\projectiles.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\props.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\meshes.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\units.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\objects.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\mods.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\loc_us.scd', '/')
mount_dir(SCFARoot .. '\\\\movies', '/movies')
mount_dir(SCFARoot .. '\\\\sounds', '/sounds')

-- =========================================================================
-- 6. User maps
-- =========================================================================
mount_dir(WOPCRoot .. '\\\\usermaps', '/maps')

-- =========================================================================
-- 7. Server-level mods (content pack mods — shared by all players)
-- =========================================================================
mount_mods(WOPCRoot .. '\\\\mods')

-- =========================================================================
-- 8. User mods (personal mods — separate namespace via mount_mods)
-- =========================================================================
mount_mods(WOPCRoot .. '\\\\usermods')

-- =========================================================================
-- Hook paths and protocols
-- =========================================================================
hook = {{
    '/schook'
}}

protocols = {{
    'http',
    'https',
}}
end
"""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(lua_content, encoding="utf-8")
    logger.info("Generated init_wopc.lua with %d gamedata mounts", len(gamedata_mounts))
    return output
