"""Dynamic init_wopc.lua generator.

Writes a fresh ``init_wopc.lua`` into ``C:\\ProgramData\\WOPC\\bin\\``
every time the user clicks **PLAY MATCH**.  This allows content packs
(gamedata SCDs) to be toggled on/off from the launcher UI — disabled
packs are simply omitted from the mount list.

The template is identical to ``init/init_wopc.lua`` in the repo, but
replaces the wildcard ``mount_dir(... '\\\\*.scd', '/')`` with explicit
lines for each enabled SCD.
"""

import logging
from pathlib import Path

from launcher import config, prefs

logger = logging.getLogger("wopc.init_generator")

# SCDs that are always mounted from WOPC/gamedata/ and never toggleable.
# In FAF-only mode (default), this is empty — faf_ui.scd provides all
# Lua code and vanilla SCFA provides units/loc.  When LOUD content packs
# are enabled, lua.scd from LOUD will be toggled on via the content pack
# system (it's now in CONTENT_PACK_LABELS).
CORE_SCDS: frozenset[str] = frozenset()

# SCDs with fixed mount positions that must NOT appear in the toggleable
# content packs list or in the early gamedata block.
_FIXED_POSITION_SCDS = frozenset({"faf_ui.scd"})

# Human-friendly names for content packs shown in the launcher UI.
# All of these are toggleable — disabled by default in FAF-only mode.
# Enabling LOUD packs requires lua.scd + loc_US.scd (LOUD overrides).
CONTENT_PACK_LABELS: dict[str, str] = {
    "lua.scd": "LOUD Lua (required for LOUD packs)",
    "loc_US.scd": "LOUD Localization",
    "4D-CompatibilityPack.scd": "4D Compatibility Pack",
    "blackops.scd": "BlackOps Units",
    "brewlan.scd": "BrewLAN Units",
    "civ_units.scd": "Civilian Units",
    "extra_env.scd": "Extra Environments",
    "loud_misc.scd": "LOUD Miscellaneous",
    "loud_units.scd": "LOUD Units",
    "SC_Music.scd": "Supreme Commander Music",
    "TotalMayhem.scd": "Total Mayhem Units",
    "units.scd": "Core Units",
    "WyvernBattlePack.scd": "Wyvern Battle Pack",
}


def get_toggleable_scds() -> list[str]:
    """Return a sorted list of gamedata SCD names the user can toggle.

    Fixed-position SCDs (faf_ui.scd) are excluded because they have
    explicit mount points in the init template and disabling them
    would corrupt VFS mount ordering.
    """
    if not config.WOPC_GAMEDATA.exists():
        return []

    all_scds = sorted(f.name for f in config.WOPC_GAMEDATA.iterdir() if f.suffix == ".scd")
    non_toggleable = CORE_SCDS | _FIXED_POSITION_SCDS
    return [s for s in all_scds if s not in non_toggleable]


def get_enabled_packs() -> list[str]:
    """Return a list of currently enabled content pack SCD names."""

    parser = prefs.load_prefs()
    if not parser.has_section("ContentPacks"):
        return []  # default: FAF-only mode (no LOUD content packs)
    enabled = []
    for scd_name in get_toggleable_scds():
        if parser.getboolean("ContentPacks", scd_name, fallback=True):
            enabled.append(scd_name)
    return enabled


def set_pack_state(scd_name: str, enabled: bool) -> None:
    """Enable or disable a content pack SCD."""
    parser = prefs.load_prefs()
    if not parser.has_section("ContentPacks"):
        parser.add_section("ContentPacks")
    parser.set("ContentPacks", scd_name, str(enabled))
    prefs.save_prefs(parser)


def generate_init_lua() -> Path:
    """Write a fresh ``init_wopc.lua`` to ``WOPC_BIN``.

    Returns the path to the generated file.
    """
    output = config.WOPC_BIN / "init_wopc.lua"

    # Determine which SCDs to mount
    enabled_packs = get_enabled_packs()
    core_on_disk = sorted(s for s in CORE_SCDS if (config.WOPC_GAMEDATA / s).exists())

    # Build the gamedata mount lines
    gamedata_mounts = []
    for scd in core_on_disk:
        gamedata_mounts.append(f"mount_dir(WOPCRoot .. '\\\\gamedata\\\\{scd}', '/')")
    for scd in enabled_packs:
        gamedata_mounts.append(f"mount_dir(WOPCRoot .. '\\\\gamedata\\\\{scd}', '/')")

    gamedata_block = "\n".join(gamedata_mounts)

    # User mods are mounted via the engine's mount_mods() function which
    # handles mod metadata, dependencies, and ordering automatically.
    # Individual mod toggling is not yet supported (requires engine work).

    lua_content = f"""\
-- =============================================================================
-- init_wopc.lua — WOPC init file (AUTO-GENERATED)
-- With Our Powers Combined: Standalone gameplay + FAF engine patches
--
-- THIS FILE IS REGENERATED BY THE LAUNCHER BEFORE EACH GAME LAUNCH.
-- Do not edit by hand — changes will be overwritten.
--
-- Mount order determines content priority (first-added = highest priority
-- for the engine's VFS file lookup — earlier mounts shadow later ones):
--   1. Bundled strategic icons  (from WOPC/bin/)
--   2. Content pack SCDs        (LOUD mods — toggleable, disabled by default)
--   3. Bundled maps and sounds
--   4. FAF UI + WOPC patches    (single SCD: FAF logic + our fixes)
--   5. Vanilla SCFA content     (fonts, textures, effects, units, loc, etc.)
--   6. User maps
--   7. User mods                (separate namespace via mount_mods)
-- =============================================================================

do
dofile(InitFileDir.."\\\\CommonDataPath.lua");

-- Resolve WOPC root: bin's parent directory
local WOPCRoot = InitFileDir .. '\\\\..'

-- Load SCFA path from generated config (written by setup.py)
-- This file sets: SCFARoot = "C:\\\\Program Files (x86)\\\\Steam\\\\..."
dofile(InitFileDir.."\\\\wopc_paths.lua");

-- =========================================================================
-- 1. Bundled strategic icons
-- =========================================================================
mount_dir(InitFileDir .. '\\\\BrewLAN-StrategicIconsOverhaul-LARGE-classic.scd', '/')

-- =========================================================================
-- 2. Content pack SCDs (LOUD mods — disabled by default)
-- =========================================================================
{gamedata_block}

-- =========================================================================
-- 3. Bundled maps and sounds
-- =========================================================================
mount_dir(WOPCRoot .. '\\\\maps', '/maps')
mount_dir(WOPCRoot .. '\\\\sounds', '/sounds')

-- =========================================================================
-- 4. FAF UI + WOPC patches (single consolidated SCD)
-- Contains FAF game logic, our WOPC fixes, and vanilla gap-fills.
-- Must be mounted BEFORE vanilla SCDs so the engine's VFS finds our
-- files first (first-added = highest priority in SCFA's VFS).
-- =========================================================================
local faf_ui = WOPCRoot .. '\\\\gamedata\\\\faf_ui.scd'
mount_dir(faf_ui, '/')

-- =========================================================================
-- 5. Vanilla SCFA content (assets + gameplay data from Steam install)
-- Mounted AFTER FAF so FAF's files take priority.  Vanilla provides
-- assets that FAF doesn't replace (unmodified units, textures, etc.).
-- FAF replaces lua.scd, mohodata.scd, moholua.scd, and schook.scd
-- with its own code in faf_ui.scd — those are NOT mounted here.
-- =========================================================================
mount_dir(SCFARoot .. '\\\\fonts', '/fonts')
mount_dir(SCFARoot .. '\\\\gamedata\\\\textures.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\effects.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\env.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\projectiles.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\props.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\meshes.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\units.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\objects.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\mods.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\loc_us.scd', '/')
mount_dir(SCFARoot .. '\\\\movies', '/movies')
mount_dir(SCFARoot .. '\\\\sounds', '/sounds')

-- =========================================================================
-- 6. User maps
-- =========================================================================
mount_dir(WOPCRoot .. '\\\\usermaps', '/maps')

-- =========================================================================
-- 7. User mods (separate namespace — loaded via mount_mods)
-- =========================================================================
mount_mods(WOPCRoot .. '\\\\usermods')

-- =========================================================================
-- Hook paths and protocols
-- =========================================================================
hook = {{
    '/schook'
}}

protocols = {{
    'http',
    'https',
}}
end
"""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(lua_content, encoding="utf-8")
    logger.info("Generated init_wopc.lua with %d gamedata mounts", len(gamedata_mounts))
    return output
