"""Dynamic init_wopc.lua generator.

Writes a fresh ``init_wopc.lua`` into ``C:\\ProgramData\\WOPC\\bin\\``
every time the user clicks **PLAY MATCH**.  This allows content packs
(gamedata SCDs) to be toggled on/off from the launcher UI — disabled
packs are simply omitted from the mount list.

The template is identical to ``init/init_wopc.lua`` in the repo, but
replaces the wildcard ``mount_dir(... '\\\\*.scd', '/')`` with explicit
lines for each enabled SCD.
"""

import logging
from pathlib import Path

from launcher import config, prefs

logger = logging.getLogger("wopc.init_generator")

# The two root modules — always mounted, never toggleable.
# These provide the base Lua engine and localization that everything else
# builds on.  Vanilla SCFA assets (effects, textures, etc.) come from Steam
# at step 5.  faf_ui.scd and wopc_patches.scd have fixed mount positions
# after vanilla SCFA and are handled explicitly in the template below.
CORE_SCDS = frozenset({"lua.scd", "loc_US.scd"})

# SCDs with fixed mount positions that must NOT appear in the toggleable
# content packs list or in the early gamedata block.
_FIXED_POSITION_SCDS = frozenset({"faf_ui.scd", "wopc_patches.scd"})

# Human-friendly names for content packs shown in the launcher UI.
CONTENT_PACK_LABELS: dict[str, str] = {
    "4D-CompatibilityPack.scd": "4D Compatibility Pack",
    "blackops.scd": "BlackOps Units",
    "brewlan.scd": "BrewLAN Units",
    "civ_units.scd": "Civilian Units",
    "extra_env.scd": "Extra Environments",
    "loud_misc.scd": "LOUD Miscellaneous",
    "loud_units.scd": "LOUD Units",
    "SC_Music.scd": "Supreme Commander Music",
    "TotalMayhem.scd": "Total Mayhem Units",
    "units.scd": "Core Units",
    "WyvernBattlePack.scd": "Wyvern Battle Pack",
}


def get_toggleable_scds() -> list[str]:
    """Return a sorted list of gamedata SCD names the user can toggle.

    Core SCDs (lua.scd, etc.) and fixed-position SCDs (faf_ui.scd,
    wopc_patches.scd) are excluded because disabling them would break
    the game or corrupt VFS mount ordering.
    """
    if not config.WOPC_GAMEDATA.exists():
        return []

    all_scds = sorted(f.name for f in config.WOPC_GAMEDATA.iterdir() if f.suffix == ".scd")
    non_toggleable = CORE_SCDS | _FIXED_POSITION_SCDS
    return [s for s in all_scds if s not in non_toggleable]


def get_enabled_packs() -> list[str]:
    """Return a list of currently enabled content pack SCD names."""

    parser = prefs.load_prefs()
    if not parser.has_section("ContentPacks"):
        return []  # default: FAF-only mode (no LOUD content packs)
    enabled = []
    for scd_name in get_toggleable_scds():
        if parser.getboolean("ContentPacks", scd_name, fallback=True):
            enabled.append(scd_name)
    return enabled


def set_pack_state(scd_name: str, enabled: bool) -> None:
    """Enable or disable a content pack SCD."""
    parser = prefs.load_prefs()
    if not parser.has_section("ContentPacks"):
        parser.add_section("ContentPacks")
    parser.set("ContentPacks", scd_name, str(enabled))
    prefs.save_prefs(parser)


def generate_init_lua() -> Path:
    """Write a fresh ``init_wopc.lua`` to ``WOPC_BIN``.

    Returns the path to the generated file.
    """
    output = config.WOPC_BIN / "init_wopc.lua"

    # Determine which SCDs to mount
    enabled_packs = get_enabled_packs()
    core_on_disk = sorted(s for s in CORE_SCDS if (config.WOPC_GAMEDATA / s).exists())

    # Build the gamedata mount lines
    gamedata_mounts = []
    for scd in core_on_disk:
        gamedata_mounts.append(f"mount_dir(WOPCRoot .. '\\\\gamedata\\\\{scd}', '/')")
    for scd in enabled_packs:
        gamedata_mounts.append(f"mount_dir(WOPCRoot .. '\\\\gamedata\\\\{scd}', '/')")

    gamedata_block = "\n".join(gamedata_mounts)

    # User mods are mounted via the engine's mount_mods() function which
    # handles mod metadata, dependencies, and ordering automatically.
    # Individual mod toggling is not yet supported (requires engine work).

    lua_content = f"""\
-- =============================================================================
-- init_wopc.lua — WOPC init file (AUTO-GENERATED)
-- With Our Powers Combined: Standalone gameplay + FAF engine patches
--
-- THIS FILE IS REGENERATED BY THE LAUNCHER BEFORE EACH GAME LAUNCH.
-- Do not edit by hand — changes will be overwritten.
--
-- Mount order determines content priority (later mounts shadow earlier ones):
--   1. Bundled strategic icons  (from WOPC/bin/)
--   2. Root modules             (lua.scd, loc_US.scd)
--   3. Content pack SCDs        (LOUD mods — toggleable, disabled by default)
--   4. Bundled maps and sounds
--   5. Vanilla SCFA content     (fonts, textures, effects, env, etc.)
--   6. FAF UI                   (shadows vanilla UI + game logic)
--   7. WOPC patches overlay     (our Lua fixes/enhancements)
--   8. User maps
--   9. User mods                (loaded LAST — shadow everything above)
-- =============================================================================

do
dofile(InitFileDir.."\\\\CommonDataPath.lua");

-- Resolve WOPC root: bin's parent directory
local WOPCRoot = InitFileDir .. '\\\\..'

-- Load SCFA path from generated config (written by setup.py)
-- This file sets: SCFARoot = "C:\\\\Program Files (x86)\\\\Steam\\\\..."
dofile(InitFileDir.."\\\\wopc_paths.lua");

-- =========================================================================
-- 1. Bundled strategic icons
-- =========================================================================
mount_dir(InitFileDir .. '\\\\BrewLAN-StrategicIconsOverhaul-LARGE-classic.scd', '/')

-- =========================================================================
-- 2-3. Root modules + enabled content packs
-- =========================================================================
{gamedata_block}

-- =========================================================================
-- 4. Bundled maps and sounds
-- =========================================================================
mount_dir(WOPCRoot .. '\\\\maps', '/maps')
mount_dir(WOPCRoot .. '\\\\sounds', '/sounds')

-- =========================================================================
-- 5. Vanilla SCFA content (fonts, textures, effects, etc.)
-- =========================================================================
mount_dir(SCFARoot .. '\\\\fonts', '/fonts')
mount_dir(SCFARoot .. '\\\\gamedata\\\\textures.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\effects.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\env.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\projectiles.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\props.scd', '/')
mount_dir(SCFARoot .. '\\\\gamedata\\\\meshes.scd', '/')
mount_dir(SCFARoot .. '\\\\movies', '/movies')
mount_dir(SCFARoot .. '\\\\sounds', '/sounds')

-- =========================================================================
-- 6. FAF UI (shadows vanilla SCFA + game logic)
-- =========================================================================
local faf_ui = WOPCRoot .. '\\\\gamedata\\\\faf_ui.scd'
mount_dir(faf_ui, '/')

-- =========================================================================
-- 7. WOPC patches overlay (shadows everything above)
-- =========================================================================
local wopc_patches = WOPCRoot .. '\\\\gamedata\\\\wopc_patches.scd'
mount_dir(wopc_patches, '/')

-- =========================================================================
-- 8. User maps
-- =========================================================================
mount_dir(WOPCRoot .. '\\\\usermaps', '/maps')

-- =========================================================================
-- 9. User mods (loaded LAST — shadow everything above)
-- =========================================================================
mount_mods(WOPCRoot .. '\\\\usermods')

-- =========================================================================
-- Hook paths and protocols
-- =========================================================================
hook = {{
    '/schook'
}}

protocols = {{
    'http',
    'https',
}}
end
"""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(lua_content, encoding="utf-8")
    logger.info("Generated init_wopc.lua with %d gamedata mounts", len(gamedata_mounts))
    return output
