"""
WOPC setup - creates the WOPC game directory and copies/symlinks content.
"""

import shutil
from pathlib import Path

from config import (
    SCFA_STEAM, SCFA_BIN, LOUD_BIN, LOUD_GAMEDATA, LOUD_MAPS, LOUD_SOUNDS,
    LOUD_USERMODS, LOUD_USERMAPS,
    WOPC_ROOT, WOPC_BIN, WOPC_GAMEDATA, WOPC_MAPS, WOPC_SOUNDS,
    WOPC_USERMODS, WOPC_USERMAPS,
    BIN_FILES, LOUD_BIN_FILES,
)


def link_or_copy(src: Path, dst: Path):
    """Create a symlink, falling back to copy if symlinks need admin."""
    if dst.exists() or dst.is_symlink():
        return  # already exists
    try:
        if src.is_dir():
            dst.symlink_to(src, target_is_directory=True)
        else:
            dst.symlink_to(src)
        print(f"  symlink {dst.name} -> {src}")
    except OSError:
        if src.is_dir():
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)
        print(f"  copied  {dst.name}")


def copy_file(src: Path, dst: Path):
    """Copy a single file, skip if already exists."""
    if dst.exists():
        return
    shutil.copy2(src, dst)
    print(f"  copied  {dst.name}")


def run_setup(repo_init_dir: Path):
    """
    Create the WOPC game directory at C:\\ProgramData\\WOPC\\ and populate it.
    repo_init_dir: path to the init/ directory in the repo (contains init_wopc.lua)
    """

    print(f"\n=== WOPC Setup v0.1 ===\n")
    print(f"WOPC directory: {WOPC_ROOT}")

    # Create directory structure
    for d in [WOPC_ROOT, WOPC_BIN, WOPC_GAMEDATA]:
        d.mkdir(parents=True, exist_ok=True)

    # --- Step 1: Copy exe + DLLs from Steam SCFA/bin/ ---
    print(f"\n[1/6] Copying game binaries from {SCFA_BIN}")
    missing = []
    for fname in BIN_FILES:
        src = SCFA_BIN / fname
        if src.exists():
            copy_file(src, WOPC_BIN / fname)
        else:
            missing.append(fname)
    if missing:
        print(f"  WARNING: missing files: {', '.join(missing)}")

    # --- Step 2: Copy LOUD bin files (icons SCD, CommonDataPath) ---
    print(f"\n[2/6] Copying LOUD bin files from {LOUD_BIN}")
    for fname in LOUD_BIN_FILES:
        src = LOUD_BIN / fname
        if src.exists():
            copy_file(src, WOPC_BIN / fname)
        else:
            print(f"  WARNING: missing {fname}")

    # --- Step 3: Copy init files from repo ---
    print(f"\n[3/6] Copying init files from repo")
    for fname in ["init_wopc.lua", "CommonDataPath.lua"]:
        src = repo_init_dir / fname
        dst = WOPC_BIN / fname
        if src.exists():
            # Always overwrite init files (they may have been updated in repo)
            shutil.copy2(src, dst)
            print(f"  copied  {fname}")
        else:
            print(f"  WARNING: missing {fname} in repo init/ directory")

    # Generate wopc_paths.lua with the absolute SCFA path
    # (WOPC lives in ProgramData, not inside SCFA, so we need this)
    scfa_escaped = str(SCFA_STEAM).replace("\\", "\\\\")
    paths_lua = WOPC_BIN / "wopc_paths.lua"
    paths_lua.write_text(
        f'-- Auto-generated by WOPC setup — do not edit\n'
        f'SCFARoot = "{scfa_escaped}"\n'
    )
    print(f"  generated wopc_paths.lua (SCFA = {SCFA_STEAM})")

    # --- Step 4: Symlink/copy LOUD content ---
    print(f"\n[4/6] Linking LOUD content")

    # Gamedata: symlink individual SCD files (not the directory itself,
    # because we'll add wopc_patches.scd alongside them)
    if LOUD_GAMEDATA.exists():
        for scd in sorted(LOUD_GAMEDATA.glob("*.scd")):
            link_or_copy(scd, WOPC_GAMEDATA / scd.name)
    else:
        print(f"  WARNING: LOUD gamedata not found at {LOUD_GAMEDATA}")

    # Maps, sounds: symlink entire directories
    if LOUD_MAPS.exists():
        link_or_copy(LOUD_MAPS, WOPC_MAPS)
    if LOUD_SOUNDS.exists():
        link_or_copy(LOUD_SOUNDS, WOPC_SOUNDS)

    # --- Step 5: Copy usermods (not symlink - user may add/remove mods) ---
    print(f"\n[5/6] Copying user mods")
    if LOUD_USERMODS.exists() and not WOPC_USERMODS.exists():
        shutil.copytree(LOUD_USERMODS, WOPC_USERMODS)
        print(f"  copied usermods/ ({sum(1 for _ in WOPC_USERMODS.rglob('*'))} files)")
    elif WOPC_USERMODS.exists():
        print(f"  usermods/ already exists, skipping")
    else:
        WOPC_USERMODS.mkdir(parents=True, exist_ok=True)
        print(f"  created empty usermods/")

    # --- Step 6: Link/create usermaps ---
    print(f"\n[6/6] Setting up user maps")
    if LOUD_USERMAPS.exists():
        link_or_copy(LOUD_USERMAPS, WOPC_USERMAPS)
    else:
        WOPC_USERMAPS.mkdir(parents=True, exist_ok=True)
        print(f"  created empty usermaps/")

    print(f"\n=== Setup complete ===")
    print(f"Game directory: {WOPC_ROOT}")
    print(f"Launch with:    python wopc.py launch")
